run:
  deadline: 2m
  skip-files: []

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 12
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - maligned
    - lll
    - dupl
    - prealloc
    - scopelint
    - wsl
    - gomnd
    - goerr113
    - testpackage
    - nestif
    - nlreturn
    - godox
    - exhaustivestruct

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude:
    - 'ST1000: at least one file in a package should have a package comment'
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
