version: '3.7'

services:
  traefik:
    image: traefik:v2.4
    ports:{{ range $port := .Ports }}
      - '{{ $port.Value }}:{{ $port.Value }}'{{ end }}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:{{ range .Labels }}
      - --{{ . }}{{ end }}
